version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_database_name
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_database_name
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  postgres_data:
